export interface CountryData {
  id: string;
  name: string;      // Jina la Nchi (Kiswahili)
  capital: string;   // Mji Mkuu (Kiswahili)
  flag: string;      // Bendera (Emoji)
  description: string; // Maelezo mafupi
}

export const africanCountries: CountryData[] = [
  { id: "1", name: "Algeria", capital: "Algiers", flag: "🇩🇿", description: "Taifa kubwa zaidi barani Afrika likiwa kaskazini." },
  { id: "2", name: "Angola", capital: "Luanda", flag: "🇦🇴", description: "Inajulikana kwa utajiri wake wa mafuta na madini kusini mwa Afrika." },
  { id: "3", name: "Benin", capital: "Porto-Novo", flag: "🇧🇯", description: "Nchi ndogo iliyopo Afrika Magharibi, asili ya dini ya Voodoo." },
  { id: "4", name: "Botswana", capital: "Gaborone", flag: "🇧🇼", description: "Moja ya nchi zenye amani na utulivu zaidi barani Afrika." },
  { id: "5", name: "Burkina Faso", capital: "Ouagadougou", flag: "🇧🇫", description: "Inamaanisha 'Nchi ya Watu Waaminifu'." },
  { id: "6", name: "Burundi", capital: "Gitega", flag: "🇧🇮", description: "Taifa dogo lenye milima mingi Afrika Mashariki." },
  { id: "7", name: "Cabo Verde", capital: "Praia", flag: "🇨🇻", description: "Fungu la visiwa lililopo katika Bahari ya Atlantiki." },
  { id: "8", name: "Cameroon", capital: "Yaoundé", flag: "🇨🇲", description: "Inajulikana kama 'Afrika Ndogo' kwa utofauti wake wa kijiografia." },
  { id: "9", name: "Jamhuri ya Afrika ya Kati", capital: "Bangui", flag: "🇨🇫", description: "Taifa lililozingirwa na nchi kavu katikati mwa Afrika." },
  { id: "10", name: "Chad", capital: "N'Djamena", flag: "🇹🇩", description: "Imepewa jina la Ziwa Chad, ni taifa kubwa lisilo na pwani." },
  { id: "11", name: "Comoros", capital: "Moroni", flag: "🇰🇲", description: "Visiwa vya volkano vilivyoko Bahari ya Hindi." },
  { id: "12", name: "Jamhuri ya Kidemokrasia ya Kongo", capital: "Kinshasa", flag: "🇨🇩", description: "Taifa kubwa sana lenye utajiri mkubwa wa maliasili." },
  { id: "13", name: "Jamhuri ya Kongo", capital: "Brazzaville", flag: "🇨🇬", description: "Nchi ipatikanayo upande wa magharibi mwa Mto Kongo." },
  { id: "14", name: "Djibouti", capital: "Djibouti", flag: "🇩🇯", description: "Nchi yenye eneo zuri la kimkakati katika Pembe ya Afrika." },
  { id: "15", name: "Misri", capital: "Cairo", flag: "🇪🇬", description: "Nyumbani kwa piramidi za kale na Mto Nile." },
  { id: "16", name: "Guinea ya Ikweta", capital: "Malabo", flag: "🇬🇶", description: "Nchi ya pekee Afrika inayozungumza Kihispania kama lugha rasmi." },
  { id: "17", name: "Eritrea", capital: "Asmara", flag: "🇪🇷", description: "Nchi iliyopo Pembe ya Afrika kando ya Bahari ya Shamu." },
  { id: "18", name: "Eswatini", capital: "Mbabane", flag: "🇸🇿", description: "Mojawapo ya nchi chache zilizobaki na ufalme kamili." },
  { id: "19", name: "Ethiopia", capital: "Addis Ababa", flag: "🇪🇹", description: "Nchi pekee Afrika ambayo haikutawaliwa kikoloni." },
  { id: "20", name: "Gabon", capital: "Libreville", flag: "🇬🇦", description: "Taifa lenye misitu minene na idadi ndogo ya watu." },
  { id: "21", name: "Gambia", capital: "Banjul", flag: "🇬🇲", description: "Nchi ndogo zaidi katika bara la Afrika (bara)." },
  { id: "22", name: "Ghana", capital: "Accra", flag: "🇬🇭", description: "Nchi ya kwanza ya kusini mwa Jangwa la Sahara kupata uhuru." },
  { id: "23", name: "Guinea", capital: "Conakry", flag: "🇬🇳", description: "Ina utajiri mkubwa wa madini ya bauxite." },
  { id: "24", name: "Guinea-Bissau", capital: "Bissau", flag: "🇬🇼", description: "Nchi ndogo ya Afrika Magharibi inayojulikana kwa mbuga zake za wanyama." },
  { id: "25", name: "Ivory Coast (Cote d'Ivoire)", capital: "Yamoussoukro", flag: "🇨🇮", description: "Mzalishaji mkuu wa kakao duniani." },
  { id: "26", name: "Kenya", capital: "Nairobi", flag: "🇰🇪", description: "Kituo kikuu cha kiuchumi na kitamaduni Afrika Mashariki." },
  { id: "27", name: "Lesotho", capital: "Maseru", flag: "🇱🇸", description: "Nchi inayozungukwa pande zote na Afrika Kusini." },
  { id: "28", name: "Liberia", capital: "Monrovia", flag: "🇱🇷", description: "Iliasisiwa na raia huru wa Marekani wenye asili ya Afrika." },
  { id: "29", name: "Libya", capital: "Tripoli", flag: "🇱🇾", description: "Taifa la kaskazini mwa Afrika linaloundwa kwa kiasi kikubwa na jangwa." },
  { id: "30", name: "Madagascar", capital: "Antananarivo", flag: "🇲🇬", description: "Kisiwa kikubwa cha nne duniani chenye viumbe vya kipekee." },
  { id: "31", name: "Malawi", capital: "Lilongwe", flag: "🇲🇼", description: "Inajulikana kama 'Moyo wa Joto wa Afrika'." },
  { id: "32", name: "Mali", capital: "Bamako", flag: "🇲🇱", description: "Zamani ilikuwa kitovu cha milki kuu ya Afrika Magharibi." },
  { id: "33", name: "Mauritania", capital: "Nouakchott", flag: "🇲🇷", description: "Inaunganisha ukanda wa Maghreb na ule wa Sahel." },
  { id: "34", name: "Mauritius", capital: "Port Louis", flag: "🇲🇺", description: "Kisiwa kizuri katika Bahari ya Hindi." },
  { id: "35", name: "Morocco", capital: "Rabat", flag: "🇲🇦", description: "Nchi ya Afrika Kaskazini yenye mchanganyiko wa tamaduni." },
  { id: "36", name: "Mozambique", capital: "Maputo", flag: "🇲🇿", description: "Ina pwani ndefu na nzuri kando ya Bahari ya Hindi." },
  { id: "37", name: "Namibia", capital: "Windhoek", flag: "🇳🇦", description: "Maarufu kwa jangwa la Namib linalokutana na bahari." },
  { id: "38", name: "Niger", capital: "Niamey", flag: "🇳🇪", description: "Sehemu kubwa ya nchi hii inafunikwa na Jangwa la Sahara." },
  { id: "39", name: "Nigeria", capital: "Abuja", flag: "🇳🇬", description: "Nchi yenye idadi kubwa zaidi ya watu barani Afrika." },
  { id: "40", name: "Rwanda", capital: "Kigali", flag: "🇷🇼", description: "Inajulikana kama 'Nchi ya Milima Elfu'." },
  { id: "41", name: "São Tomé na Príncipe", capital: "São Tomé", flag: "🇸🇹", description: "Taifa la kisiwa kidogo Afrika ya Kati." },
  { id: "42", name: "Senegal", capital: "Dakar", flag: "🇸🇳", description: "Lango la kufikia Afrika Magharibi." },
  { id: "43", name: "Seychelles", capital: "Victoria", flag: "🇸🇨", description: "Fungu la visiwa vya paradiso katika Bahari ya Hindi." },
  { id: "44", name: "Sierra Leone", capital: "Freetown", flag: "🇸🇱", description: "Maarufu kwa ufukwe wake mweupe na mazingira ya kuvutia." },
  { id: "45", name: "Somalia", capital: "Mogadishu", flag: "🇸🇴", description: "Nchi yenye pwani ndefu zaidi katika bara la Afrika." },
  { id: "46", name: "Afrika Kusini", capital: "Pretoria", flag: "🇿🇦", description: "Inajulikana kama 'Taifa la Upinde wa Mvua'." },
  { id: "47", name: "Sudan Kusini", capital: "Juba", flag: "🇸🇸", description: "Taifa jipya zaidi duniani, lililopata uhuru mwaka 2011." },
  { id: "48", name: "Sudan", capital: "Khartoum", flag: "🇸🇩", description: "Mahali ambapo mto Nile Mweupe na mto Nile wa Bluu hukutana." },
  { id: "49", name: "Tanzania", capital: "Dodoma", flag: "🇹🇿", description: "Nyumbani kwa Mlima Kilimanjaro na Mbuga ya Serengeti." },
  { id: "50", name: "Togo", capital: "Lomé", flag: "🇹🇬", description: "Nchi ndogo lakini ndefu Afrika Magharibi." },
  { id: "51", name: "Tunisia", capital: "Tunis", flag: "🇹🇳", description: "Nchi ya Kaskazini mwa Afrika iliyopakana na Bahari ya Mediterania." },
  { id: "52", name: "Uganda", capital: "Kampala", flag: "🇺🇬", description: "Winston Churchill aliita nchi hii 'Lulu ya Afrika'." },
  { id: "53", name: "Zambia", capital: "Lusaka", flag: "🇿🇲", description: "Inajulikana sana kwa Maporomoko ya Victoria (Victoria Falls)." },
  { id: "54", name: "Zimbabwe", capital: "Harare", flag: "🇿🇼", description: "Pia ina sehemu ya Maporomoko ya Victoria na magofu ya Great Zimbabwe." }
];
